sonar.organization=YOUR_ORGANIZATION_KEY_HERE
sonar.projectKey=guess-number
sonar.projectName=guess-number
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,guess/**,static/**,templates/**,*.db
sonar.python.version=3.12
