sonar.projectKey=guess-number
sonar.projectName=guess-number
sonar.sources=.
sonar.tests=tests
sonar.exclusions=tests/**,guess/**,static/**,templates/**,*.db,coverage.xml
sonar.python.version=3.12
sonar.python.coverage.reportPaths=coverage.xml
